#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : astroid
Version  : 2.4.0
Release  : 93
URL      : https://files.pythonhosted.org/packages/c7/77/b63d5956ffaa237981fa99f902d1963f2c097c1dd9700447b4815dedceb9/astroid-2.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c7/77/b63d5956ffaa237981fa99f902d1963f2c097c1dd9700447b4815dedceb9/astroid-2.4.0.tar.gz
Summary  : a graphical threads-with-tags style, lightweight and fast, email client for notmuch, inspired by sup and others
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: astroid-license = %{version}-%{release}
Requires: astroid-python = %{version}-%{release}
Requires: astroid-python3 = %{version}-%{release}
Requires: lazy-object-proxy
Requires: six
Requires: typed_ast
Requires: wrapt
BuildRequires : buildreq-distutils3
BuildRequires : lazy-object-proxy
BuildRequires : logilab-common
BuildRequires : six
BuildRequires : typed_ast
BuildRequires : wrapt

%description
Astroid
=======
.. image:: https://travis-ci.org/PyCQA/astroid.svg?branch=master
:target: https://travis-ci.org/PyCQA/astroid

%package license
Summary: license components for the astroid package.
Group: Default

%description license
license components for the astroid package.


%package python
Summary: python components for the astroid package.
Group: Default
Requires: astroid-python3 = %{version}-%{release}

%description python
python components for the astroid package.


%package python3
Summary: python3 components for the astroid package.
Group: Default
Requires: python3-core
Provides: pypi(astroid)
Requires: pypi(lazy_object_proxy)
Requires: pypi(six)
Requires: pypi(wrapt)

%description python3
python3 components for the astroid package.


%prep
%setup -q -n astroid-2.4.0
cd %{_builddir}/astroid-2.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1587995430
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python -m unittest discover -s astroid/tests -p "unittest*.py" || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/astroid
cp %{_builddir}/astroid-2.4.0/COPYING %{buildroot}/usr/share/package-licenses/astroid/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/astroid-2.4.0/COPYING.LESSER %{buildroot}/usr/share/package-licenses/astroid/9a1929f4700d2407c70b507b3b2aaf6226a9543c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/astroid/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/astroid/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
